---
- hosts: remoto
  gather_facts: True

  tasks:
  - name: Run Command
    command: sh /home/vagrant/iaac_slacko-api/mongo.sh


  - name: Enable and start mongodb service
    systemd:
        state: started
        name: mongod
        enabled: yes

  - name: Install dependencies
    command: python3 -m pip install -r requeriments.txt

  - name: Run app
    command: sh /home/vagrant/iaac_slacko-api/slacko-api.sh
